"""Add KYC verification table

Revision ID: f1c2e9942422
Revises: 9844dd8cdaa9
Create Date: 2026-07-20 19:27:54.682875
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c2e9942422'
down_revision: Union[str, None] = '9844dd8cdaa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_front_url', sa.String(length=500), nullable=True),
    sa.Column('document_back_url', sa.String(length=500), nullable=True),
    sa.Column('selfie_url', sa.String(length=500), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_verifications_user_id'), 'kyc_verifications', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_verifications_user_id'), table_name='kyc_verifications')
    op.drop_table('kyc_verifications')
    # ### end Alembic commands ###
