"""add admin_role column to users

Revision ID: fbe62f0ec52b
Revises: fe4fc10ed5c8
Create Date: 2026-07-21 01:26:53.861806
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe62f0ec52b'
down_revision: Union[str, None] = 'fe4fc10ed5c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('admin_username', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_table('bonuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bonus_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('match_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_bonus_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('flat_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('free_spins_count', sa.Integer(), nullable=True),
    sa.Column('wagering_multiplier', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_bet_with_bonus', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_deposit_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('eligible_games', sa.Text(), nullable=True),
    sa.Column('is_repeatable', sa.Boolean(), nullable=False),
    sa.Column('max_claims_per_user', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonuses_bonus_type'), 'bonuses', ['bonus_type'], unique=False)
    op.create_table('game_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('min_bet', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('max_bet', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('default_bet', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('rtp_adjustment', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_configs_game_type'), 'game_configs', ['game_type'], unique=True)
    op.create_table('platform_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('announcement_enabled', sa.Boolean(), nullable=False),
    sa.Column('announcement_text', sa.Text(), nullable=True),
    sa.Column('announcement_type', sa.String(length=20), nullable=False),
    sa.Column('min_withdrawal', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('max_withdrawal', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('daily_withdrawal_limit', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('deposit_fee_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('withdrawal_fee_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('withdrawal_fee_fixed', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('supported_currencies', sa.String(length=255), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_bonuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bonus_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('awarded_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('wagered_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('required_wager', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_forfeited', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bonus_id'], ['bonuses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bonuses_bonus_id'), 'user_bonuses', ['bonus_id'], unique=False)
    op.create_index(op.f('ix_user_bonuses_user_id'), 'user_bonuses', ['user_id'], unique=False)
    op.add_column('users', sa.Column('admin_role', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_role')
    op.drop_index(op.f('ix_user_bonuses_user_id'), table_name='user_bonuses')
    op.drop_index(op.f('ix_user_bonuses_bonus_id'), table_name='user_bonuses')
    op.drop_table('user_bonuses')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_game_configs_game_type'), table_name='game_configs')
    op.drop_table('game_configs')
    op.drop_index(op.f('ix_bonuses_bonus_type'), table_name='bonuses')
    op.drop_table('bonuses')
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
